### PR TITLE
PETBUILD for util-linux

### PR DESCRIPTION
**Pull request by TrulyEqilia**
Due to the... (delicately saying) enormous size of the PETBUILD, I'd honestly much rather prefer that the port is reviewed.

### CODE REVIEW

**Comment by n1d3v** [comment]
Does it work properly? Does it build successfully?

**Comment by TrulyEqilia** [comment]
> Does it work properly? Does it build successfully?

Yep, obviously. It's the least of QA I could have done, although petbuild isn't yet updated with the variables that are used here, so thank you for reminding me of that.
I'll update petbuild ^w^

**Comment by TrulyEqilia** [comment]
@n1d3v Fixed in 974ee84c3452

**Review by n1d3v — COMMENTED** [review]
Looks good. I would push to the main branch.

**Comment by TrulyEqilia** [comment]
Thanks ^^

**Pull request merged**
